### ISSUE TITLE
rspec fails with 2 errors on Mac :)

### ISSUE THREAD

**Issue by lacostej** [machinio/cuprite#51]
````
Failures:

  1) Capybara::Cuprite::Driver has ability to send keys sends sequences with modifiers and symbols
     Failure/Error: expect(input.value).to eq("string")
     
       expected: "string"
            got: "trings"
     
       (compared using ==)
     # ./spec/integration/driver_spec.rb:1303:in `block (3 levels) in <module:Cuprite>'
     # ./spec/integration/driver_spec.rb:14:in `block (2 levels) in <module:Cuprite>'

  2) Capybara::Cuprite::Driver has ability to send keys sends sequences with multiple modifiers and symbols
     Failure/Error: expect(input.value).to eq("s")
     
       expected: "s"
            got: "trings"
     
       (compared using ==)
     # ./spec/integration/driver_spec.rb:1311:in `block (3 levels) in <module:Cuprite>'
     # ./spec/integration/driver_spec.rb:14:in `block (2 levels) in <module:Cuprite>'

Finished in 8 minutes 28 seconds (files took 1.14 seconds to load)
1555 examples, 2 failures, 26 pending

Failed examples:

rspec ./spec/integration/driver_spec.rb:1298 # Capybara::Cuprite::Driver has ability to send keys sends sequences with modifiers and symbols
rspec ./spec/integration/driver_spec.rb:1306 # Capybara::Cuprite::Driver has ability to send keys sends sequences with multiple modifiers and symbols
````

**Comment by route** [comment]
That's on macos only, for some reason send keys for modifiers doesn't work properly on mac

**Comment by route** [comment]
Merged your fix, so closing this. Thanks!
