### ISSUE TITLE
rspec fails with Capybara::Cuprite::NoSuchWindowError on CI

### ISSUE THREAD

**Issue by senid231** [machinio/cuprite#95]
cuprite version 0.6.0
google-chrome-stable version 73
docker container

during rspec tests run  I've `execution expired` on some feature test
after that all other feature tests fail with `Capybara::Cuprite::NoSuchWindowError`
as result CI hangs for more than a hour and worker just kills it, so I don't have detailed logs about what's happened there. I on CI it fails randomly (aproximately once per 20 runs) and I can't reproduce it on my local machine.

Did someone encountered with such problem? Maybe any suggestions how to debug it?

**Comment by route** [comment]
Let’s start with master branch, could you please try running cuprite from master?

**Comment by senid231** [comment]
@route thanks for quick response.
I've used master and got `Ferrum::NoSuchWindowError` on second CI run.

first test in suite fail with `Ferrum::NoExecutionContextError`
after that all test fail with `Ferrum::NoSuchWindowError`

**Comment by senid231** [comment]
BTW I'm using `rspec-retry` with following callback for proper session resetting
```ruby
config.retry_callback = proc do |example|
    $stderr.puts "RETRY EXAMPLE #{example.full_description.inspect}"
    # avoid Capybara::Cuprite::NoSuchWindowError
    if example.metadata[:js]
      Capybara.reset_sessions!
      Capybara.current_driver = Capybara.javascript_driver
      Capybara.current_driver = example.metadata[:driver] if example.metadata[:driver]
    end
  end
```

**Comment by route** [comment]
@senid231 if you can run tests with logger debug that would ease the whole thing

**Comment by senid231** [comment]
@route I've send you debug log via email

**Comment by route** [comment]
Hey Denis do you still have issues with you test suit?

**Comment by vladimirtemnikov** [comment]
@route I have the same problem
Sometimes tests fail with `Ferrum::NoSuchWindowError`, not figured out why yet.

```
Failure/Error: visit domain_management

     Ferrum::NoExecutionContextError:
       There's no context available
     # ./.bundle/ruby/2.5.0/gems/ferrum-0.5/lib/ferrum/page/frame.rb:10:in `execution_context_id'
     # ./.bundle/ruby/2.5.0/gems/ferrum-0.5/lib/ferrum/page.rb:217:in `block in inject_extensions'
     # ./.bundle/ruby/2.5.0/gems/ferrum-0.5/lib/ferrum/page.rb:210:in `each'
     # ./.bundle/ruby/2.5.0/gems/ferrum-0.5/lib/ferrum/page.rb:210:in `inject_extensions'
     # ./.bundle/ruby/2.5.0/gems/ferrum-0.5/lib/ferrum/page.rb:193:in `prepare_page'
     # ./.bundle/ruby/2.5.0/gems/cuprite-0.7.1/lib/capybara/cuprite/page.rb:110:in `prepare_page'
     # ./.bundle/ruby/2.5.0/gems/ferrum-0.5/lib/ferrum/page.rb:56:in `initialize'
     # ./.bundle/ruby/2.5.0/gems/cuprite-0.7.1/lib/capybara/cuprite/page.rb:8:in `initialize'
     # ./.bundle/ruby/2.5.0/gems/ferrum-0.5/lib/ferrum/target.rb:20:in `new'
     # ./.bundle/ruby/2.5.0/gems/ferrum-0.5/lib/ferrum/target.rb:20:in `page'
     # ./.bundle/ruby/2.5.0/gems/ferrum-0.5/lib/ferrum/context.rb:22:in `page'
     # ./.bundle/ruby/2.5.0/gems/cuprite-0.7.1/lib/capybara/cuprite/browser.rb:35:in `visit'
     # ./.bundle/ruby/2.5.0/gems/cuprite-0.7.1/lib/capybara/cuprite/driver.rb:41:in `visit'
     # ./.bundle/ruby/2.5.0/gems/capybara-3.29.0/lib/capybara/session.rb:276:in `visit'
     # ./.bundle/ruby/2.5.0/gems/capybara-3.29.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/admin/reseller_domain_spec.rb:46:in `block (3 levels) in <top (required)>'
```

**Comment by route** [comment]
@vladimirtemnikov there's even no such error in newest releases. You should try using master upgrade to latest versions both gems.

**Comment by vladimirtemnikov** [comment]
@route thank you, I'll try!

**Comment by LosBandolero** [comment]
@route good afternoon, I do experience this issue right now and can not switch to iframe, all the information is bellow:

1. Gems and versions: 
`gem 'capybara', '3.35.3'
gem 'cuprite', '0.13'
em 'rspec', '3.10.0'
gem 'site_prism', '3.7.3'`

2. Error Log
`Failure/Error: raise NoExecutionContextError unless @execution_id

          Ferrum::NoExecutionContextError:
            There's no context available
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ferrum-0.11/lib/ferrum/frame.rb:52:in `execution_id'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ferrum-0.11/lib/ferrum/frame/runtime.rb:134:in `block in call'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ferrum-0.11/lib/ferrum.rb:145:in `with_attempts'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ferrum-0.11/lib/ferrum/frame/runtime.rb:124:in `call'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ferrum-0.11/lib/ferrum/frame/runtime.rb:50:in `evaluate'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ferrum-0.11/lib/ferrum/frame/dom.rb:24:in `current_url'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `current_url'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `current_url'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cuprite-0.13/lib/capybara/cuprite/driver.rb:50:in `current_url'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/capybara-3.35.3/lib/capybara/session.rb:229:in `current_url'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/capybara-screenshot-1.0.25/lib/capybara-screenshot/rspec.rb:56:in `block in after_failed_example'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/capybara-3.35.3/lib/capybara.rb:371:in `using_session'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/capybara-screenshot-1.0.25/lib/capybara-screenshot/capybara.rb:7:in `using_session'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/capybara-screenshot-1.0.25/lib/capybara-screenshot/rspec.rb:55:in `after_failed_example'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/capybara-screenshot-1.0.25/lib/capybara-screenshot/rspec.rb:105:in `block (2 levels) in <top (required)>'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:372:in `run'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:529:in `block in run_owned_hooks_for'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:528:in `each'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:528:in `run_owned_hooks_for'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:615:in `block in run_example_hooks_for'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:614:in `each'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:614:in `run_example_hooks_for'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:485:in `run'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:515:in `run_after_example'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:281:in `block in run'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `block in run'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `run'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:259:in `run'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:644:in `block in run_examples'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `map'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `run_examples'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:606:in `run'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `map'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2067:in `with_suite_hooks'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:89:in `run'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<top (required)>'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/bin/rspec:23:in `load'
          # /Users/grigoravagyan/.rbenv/versions/2.7.2/bin/rspec:23:in `<main>'`

**Comment by route** [comment]
@LosBandolero can you run this test in particular with `CUPRITE_DEBUG=true` and show the output here?
